# Shared Linux home-manager bits (Arch + NixOS). Imports the shared config and
# adds the pieces common to both Linux targets, plus Linux-specific slices of
# the per-program modules (kitty theme, Arch zsh).
{ pkgs, lib, ... }:

{
  imports = [ ./common.nix ];

  home.packages = with pkgs; [
    gcc       # C compiler for nvim-treesitter parser builds
    xdg-utils # provides `xdg-open`, used by the Neovim config's image/PDF open
  ];

  # kitty theme is generated by quickshell (hyprland setup) on Linux; kitty.conf
  # ships no theme so macOS stays clean. Appended after the shared kitty config.
  programs.kitty.extraConfig = lib.mkAfter ''
    include ~/.local/state/quickshell/user/generated/terminal/kitty-theme.conf
  '';

  # Arch-specific zsh — the shared base (home/packages/zsh/zsh.nix) already gives
  # a working zsh (history, completion, autosuggestions, syntax highlighting,
  # oh-my-posh); only the Linux-only bits live here.
  #
  # nvhypr: hypr config is NOT yet in the dotfiles, so this still points at
  # ~/.config/hypr. When hypr gets folded into nix+hm (planned), repoint it the
  # way nvconf now targets the vendored nvim config.
  programs.zsh.shellAliases = {
    nvhypr = "cd ~/.config/hypr && nvim . && cd -";
    # macOS binds claudio -> `claude` (work); on Linux it's plain claude.
    claudio = "claude";
  };

  programs.zsh.initContent = lib.mkAfter ''
    # Delete key + Ctrl+Left/Right word navigation (xterm/kitty sequences)
    bindkey "^[[3~" delete-char
    bindkey "^[[1;5C" forward-word
    bindkey "^[[1;5D" backward-word

    # esp-idf: source the SDK env on demand (lazy — no startup cost). First run
    # also registers /opt/esp-idf as a git safe.directory (idempotent).
    esp() {
      git config --global --get-all safe.directory \
        | grep -q '^/opt/esp-idf$' \
        || git config --global --add safe.directory /opt/esp-idf
      source /opt/esp-idf/export.sh
    }
  '';
}
